### ISSUE TITLE
No showing in Product list

### ISSUE THREAD

**Issue by sbakker12** [springimport/magento2-module-catalog-dropdown-sort#1]
Hi, i installed your extension but is its not showing in the frontend. How can i fix this?

**Comment by springimport** [comment]
Hi, @sbakker12

I fixed this mistake ([commit](https://github.com/springimport/magento2-module-catalog-dropdown-sort/commit/947a69aed3e4a3ef697bef8a20813116c71ce305)). You can update module from `dev-master`.

Thank you.
