### ISSUE TITLE
please help check it only show 2 type option

### ISSUE THREAD

**Issue by kytan91** [springimport/magento2-module-catalog-dropdown-sort#2]
Hi, 
after i install it only shows up 2 options, my magento version is 2.1.7, is there any setting at the admin panel? how can i shows up another 2 options. Thanks!
![2017-07-13_16-17-16](https://user-images.githubusercontent.com/30074078/28156957-61fa26a4-67e7-11e7-938b-2a22f923c9af.jpg)

**Comment by springimport** [comment]
@kytan91 Yes, I extend default component and you can manage options from Magento Admin.

Stores > Attributes > Product > [select attribute] > Storefront Preferences > Used for Sorting in Product Listing = Yes, Position = 1.

**Comment by kytan91** [comment]
Thanks for reply. 
Alright Thanks!
can i know how to set default sorting by newest products first ?

**Comment by springimport** [comment]
@kytan91 I'm don't know how you can change default sorting, but for sorting by newest use news_from_date attribute.
